### ISSUE TITLE
Change the waves speed and resize on running = false

### ISSUE THREAD

**Issue by MiquelGatiusF** [isuttell/sine-waves#5]
As you can see in the title i need to modify the speed of a canvas, my problem is the canvas dissapear when you resize the browser. That happens when i turn the wave.running to false..
wave.speed = 0; doesn't work.

**Comment by MiquelGatiusF** [comment]
Created a function on.resize() to redraw everything again.

**Comment by tiansial** [comment]
> Created a function on.resize() to redraw everything again.

you mind sharing how did you redraw the whole thing on resize?
